version: "3"
services:
  bizcard:
    platform: linux/x86_64 # 추가된 라인
    image: library/mysql:5.7
    container_name: bizcard
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      TZ: Asia/Seoul
    volumes:
      - ./mysql/datadir:/var/lib/mysql
    command: >
      mysql -uroot -psecret -e "CREATE DATBASE bizcardtest"
      
