// Code generated by mockery v2.10.0. DO NOT EDIT.

package repository

import (
	domain "bizCard/domain"
	ent "bizCard/ent"

	mock "github.com/stretchr/testify/mock"
)

// MockBizCardRepository is an autogenerated mock type for the BizCardRepository type
type MockBizCardRepository struct {
	mock.Mock
}

// RegisterBizCard provides a mock function with given fields: dto
func (_m *MockBizCardRepository) RegisterBizCard(dto *domain.BizCardRegister) (*ent.BizCard, error) {
	ret := _m.Called(dto)

	var r0 *ent.BizCard
	if rf, ok := ret.Get(0).(func(*domain.BizCardRegister) *ent.BizCard); ok {
		r0 = rf(dto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.BizCard)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.BizCardRegister) error); ok {
		r1 = rf(dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
