// Code generated by mockery v2.10.0. DO NOT EDIT.

package repository

import (
	domain "bizCard/domain"
	ent "bizCard/ent"

	mock "github.com/stretchr/testify/mock"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

// RegisterUser provides a mock function with given fields: userRegister
func (_m *MockUserRepository) RegisterUser(userRegister domain.UserRegister) (*ent.User, error) {
	ret := _m.Called(userRegister)

	var r0 *ent.User
	if rf, ok := ret.Get(0).(func(domain.UserRegister) *ent.User); ok {
		r0 = rf(userRegister)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.UserRegister) error); ok {
		r1 = rf(userRegister)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
