// Code generated by mockery v2.10.0. DO NOT EDIT.

package repository

import (
	domain "bizCard/domain"
	ent "bizCard/ent"

	mock "github.com/stretchr/testify/mock"
)

// MockBizCardRepository is an autogenerated mock type for the BizCardRepository type
type MockBizCardRepository struct {
	mock.Mock
}

// DeleteBizCardByUid provides a mock function with given fields: uid
func (_m *MockBizCardRepository) DeleteBizCardByUid(uid int) error {
	ret := _m.Called(uid)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindBIzCardByUid provides a mock function with given fields: uid
func (_m *MockBizCardRepository) FindBIzCardByUid(uid int) (*ent.BizCard, error) {
	ret := _m.Called(uid)

	var r0 *ent.BizCard
	if rf, ok := ret.Get(0).(func(int) *ent.BizCard); ok {
		r0 = rf(uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.BizCard)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterBizCard provides a mock function with given fields: dto
func (_m *MockBizCardRepository) RegisterBizCard(dto *domain.BizCardRegister) (*ent.BizCard, error) {
	ret := _m.Called(dto)

	var r0 *ent.BizCard
	if rf, ok := ret.Get(0).(func(*domain.BizCardRegister) *ent.BizCard); ok {
		r0 = rf(dto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.BizCard)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.BizCardRegister) error); ok {
		r1 = rf(dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBizCard provides a mock function with given fields: uid, bizCardUpdate
func (_m *MockBizCardRepository) UpdateBizCard(uid int, bizCardUpdate *domain.BizCardUpdate) (*ent.BizCard, error) {
	ret := _m.Called(uid, bizCardUpdate)

	var r0 *ent.BizCard
	if rf, ok := ret.Get(0).(func(int, *domain.BizCardUpdate) *ent.BizCard); ok {
		r0 = rf(uid, bizCardUpdate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.BizCard)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, *domain.BizCardUpdate) error); ok {
		r1 = rf(uid, bizCardUpdate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
