// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BizCardsColumns holds the columns for the "biz_cards" table.
	BizCardsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "phone_number", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "age", Type: field.TypeInt},
	}
	// BizCardsTable holds the schema information for the "biz_cards" table.
	BizCardsTable = &schema.Table{
		Name:       "biz_cards",
		Columns:    BizCardsColumns,
		PrimaryKey: []*schema.Column{BizCardsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BizCardsTable,
	}
)

func init() {
}
