// Code generated by entc, DO NOT EDIT.

package ent

import (
	"bizCard/ent/bizcard"
	"bizCard/ent/predicate"
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BizCardQuery is the builder for querying BizCard entities.
type BizCardQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.BizCard
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BizCardQuery builder.
func (bcq *BizCardQuery) Where(ps ...predicate.BizCard) *BizCardQuery {
	bcq.predicates = append(bcq.predicates, ps...)
	return bcq
}

// Limit adds a limit step to the query.
func (bcq *BizCardQuery) Limit(limit int) *BizCardQuery {
	bcq.limit = &limit
	return bcq
}

// Offset adds an offset step to the query.
func (bcq *BizCardQuery) Offset(offset int) *BizCardQuery {
	bcq.offset = &offset
	return bcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bcq *BizCardQuery) Unique(unique bool) *BizCardQuery {
	bcq.unique = &unique
	return bcq
}

// Order adds an order step to the query.
func (bcq *BizCardQuery) Order(o ...OrderFunc) *BizCardQuery {
	bcq.order = append(bcq.order, o...)
	return bcq
}

// First returns the first BizCard entity from the query.
// Returns a *NotFoundError when no BizCard was found.
func (bcq *BizCardQuery) First(ctx context.Context) (*BizCard, error) {
	nodes, err := bcq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{bizcard.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bcq *BizCardQuery) FirstX(ctx context.Context) *BizCard {
	node, err := bcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BizCard ID from the query.
// Returns a *NotFoundError when no BizCard ID was found.
func (bcq *BizCardQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bcq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{bizcard.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bcq *BizCardQuery) FirstIDX(ctx context.Context) int {
	id, err := bcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BizCard entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BizCard entity is found.
// Returns a *NotFoundError when no BizCard entities are found.
func (bcq *BizCardQuery) Only(ctx context.Context) (*BizCard, error) {
	nodes, err := bcq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{bizcard.Label}
	default:
		return nil, &NotSingularError{bizcard.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bcq *BizCardQuery) OnlyX(ctx context.Context) *BizCard {
	node, err := bcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BizCard ID in the query.
// Returns a *NotSingularError when more than one BizCard ID is found.
// Returns a *NotFoundError when no entities are found.
func (bcq *BizCardQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bcq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{bizcard.Label}
	default:
		err = &NotSingularError{bizcard.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bcq *BizCardQuery) OnlyIDX(ctx context.Context) int {
	id, err := bcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BizCards.
func (bcq *BizCardQuery) All(ctx context.Context) ([]*BizCard, error) {
	if err := bcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return bcq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (bcq *BizCardQuery) AllX(ctx context.Context) []*BizCard {
	nodes, err := bcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BizCard IDs.
func (bcq *BizCardQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := bcq.Select(bizcard.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bcq *BizCardQuery) IDsX(ctx context.Context) []int {
	ids, err := bcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bcq *BizCardQuery) Count(ctx context.Context) (int, error) {
	if err := bcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return bcq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (bcq *BizCardQuery) CountX(ctx context.Context) int {
	count, err := bcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bcq *BizCardQuery) Exist(ctx context.Context) (bool, error) {
	if err := bcq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return bcq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (bcq *BizCardQuery) ExistX(ctx context.Context) bool {
	exist, err := bcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BizCardQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bcq *BizCardQuery) Clone() *BizCardQuery {
	if bcq == nil {
		return nil
	}
	return &BizCardQuery{
		config:     bcq.config,
		limit:      bcq.limit,
		offset:     bcq.offset,
		order:      append([]OrderFunc{}, bcq.order...),
		predicates: append([]predicate.BizCard{}, bcq.predicates...),
		// clone intermediate query.
		sql:    bcq.sql.Clone(),
		path:   bcq.path,
		unique: bcq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BizCard.Query().
//		GroupBy(bizcard.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (bcq *BizCardQuery) GroupBy(field string, fields ...string) *BizCardGroupBy {
	group := &BizCardGroupBy{config: bcq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := bcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return bcq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.BizCard.Query().
//		Select(bizcard.FieldName).
//		Scan(ctx, &v)
//
func (bcq *BizCardQuery) Select(fields ...string) *BizCardSelect {
	bcq.fields = append(bcq.fields, fields...)
	return &BizCardSelect{BizCardQuery: bcq}
}

func (bcq *BizCardQuery) prepareQuery(ctx context.Context) error {
	for _, f := range bcq.fields {
		if !bizcard.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bcq.path != nil {
		prev, err := bcq.path(ctx)
		if err != nil {
			return err
		}
		bcq.sql = prev
	}
	return nil
}

func (bcq *BizCardQuery) sqlAll(ctx context.Context) ([]*BizCard, error) {
	var (
		nodes = []*BizCard{}
		_spec = bcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &BizCard{config: bcq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, bcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (bcq *BizCardQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bcq.querySpec()
	_spec.Node.Columns = bcq.fields
	if len(bcq.fields) > 0 {
		_spec.Unique = bcq.unique != nil && *bcq.unique
	}
	return sqlgraph.CountNodes(ctx, bcq.driver, _spec)
}

func (bcq *BizCardQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := bcq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (bcq *BizCardQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   bizcard.Table,
			Columns: bizcard.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: bizcard.FieldID,
			},
		},
		From:   bcq.sql,
		Unique: true,
	}
	if unique := bcq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := bcq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bizcard.FieldID)
		for i := range fields {
			if fields[i] != bizcard.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bcq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bcq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bcq *BizCardQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bcq.driver.Dialect())
	t1 := builder.Table(bizcard.Table)
	columns := bcq.fields
	if len(columns) == 0 {
		columns = bizcard.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bcq.sql != nil {
		selector = bcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bcq.unique != nil && *bcq.unique {
		selector.Distinct()
	}
	for _, p := range bcq.predicates {
		p(selector)
	}
	for _, p := range bcq.order {
		p(selector)
	}
	if offset := bcq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bcq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BizCardGroupBy is the group-by builder for BizCard entities.
type BizCardGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bcgb *BizCardGroupBy) Aggregate(fns ...AggregateFunc) *BizCardGroupBy {
	bcgb.fns = append(bcgb.fns, fns...)
	return bcgb
}

// Scan applies the group-by query and scans the result into the given value.
func (bcgb *BizCardGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := bcgb.path(ctx)
	if err != nil {
		return err
	}
	bcgb.sql = query
	return bcgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (bcgb *BizCardGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := bcgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (bcgb *BizCardGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(bcgb.fields) > 1 {
		return nil, errors.New("ent: BizCardGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := bcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (bcgb *BizCardGroupBy) StringsX(ctx context.Context) []string {
	v, err := bcgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (bcgb *BizCardGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = bcgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{bizcard.Label}
	default:
		err = fmt.Errorf("ent: BizCardGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (bcgb *BizCardGroupBy) StringX(ctx context.Context) string {
	v, err := bcgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (bcgb *BizCardGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(bcgb.fields) > 1 {
		return nil, errors.New("ent: BizCardGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := bcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (bcgb *BizCardGroupBy) IntsX(ctx context.Context) []int {
	v, err := bcgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (bcgb *BizCardGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = bcgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{bizcard.Label}
	default:
		err = fmt.Errorf("ent: BizCardGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (bcgb *BizCardGroupBy) IntX(ctx context.Context) int {
	v, err := bcgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (bcgb *BizCardGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(bcgb.fields) > 1 {
		return nil, errors.New("ent: BizCardGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := bcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (bcgb *BizCardGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := bcgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (bcgb *BizCardGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = bcgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{bizcard.Label}
	default:
		err = fmt.Errorf("ent: BizCardGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (bcgb *BizCardGroupBy) Float64X(ctx context.Context) float64 {
	v, err := bcgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (bcgb *BizCardGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(bcgb.fields) > 1 {
		return nil, errors.New("ent: BizCardGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := bcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (bcgb *BizCardGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := bcgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (bcgb *BizCardGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = bcgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{bizcard.Label}
	default:
		err = fmt.Errorf("ent: BizCardGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (bcgb *BizCardGroupBy) BoolX(ctx context.Context) bool {
	v, err := bcgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (bcgb *BizCardGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range bcgb.fields {
		if !bizcard.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := bcgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bcgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (bcgb *BizCardGroupBy) sqlQuery() *sql.Selector {
	selector := bcgb.sql.Select()
	aggregation := make([]string, 0, len(bcgb.fns))
	for _, fn := range bcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(bcgb.fields)+len(bcgb.fns))
		for _, f := range bcgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(bcgb.fields...)...)
}

// BizCardSelect is the builder for selecting fields of BizCard entities.
type BizCardSelect struct {
	*BizCardQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (bcs *BizCardSelect) Scan(ctx context.Context, v interface{}) error {
	if err := bcs.prepareQuery(ctx); err != nil {
		return err
	}
	bcs.sql = bcs.BizCardQuery.sqlQuery(ctx)
	return bcs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (bcs *BizCardSelect) ScanX(ctx context.Context, v interface{}) {
	if err := bcs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (bcs *BizCardSelect) Strings(ctx context.Context) ([]string, error) {
	if len(bcs.fields) > 1 {
		return nil, errors.New("ent: BizCardSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := bcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (bcs *BizCardSelect) StringsX(ctx context.Context) []string {
	v, err := bcs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (bcs *BizCardSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = bcs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{bizcard.Label}
	default:
		err = fmt.Errorf("ent: BizCardSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (bcs *BizCardSelect) StringX(ctx context.Context) string {
	v, err := bcs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (bcs *BizCardSelect) Ints(ctx context.Context) ([]int, error) {
	if len(bcs.fields) > 1 {
		return nil, errors.New("ent: BizCardSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := bcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (bcs *BizCardSelect) IntsX(ctx context.Context) []int {
	v, err := bcs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (bcs *BizCardSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = bcs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{bizcard.Label}
	default:
		err = fmt.Errorf("ent: BizCardSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (bcs *BizCardSelect) IntX(ctx context.Context) int {
	v, err := bcs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (bcs *BizCardSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(bcs.fields) > 1 {
		return nil, errors.New("ent: BizCardSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := bcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (bcs *BizCardSelect) Float64sX(ctx context.Context) []float64 {
	v, err := bcs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (bcs *BizCardSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = bcs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{bizcard.Label}
	default:
		err = fmt.Errorf("ent: BizCardSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (bcs *BizCardSelect) Float64X(ctx context.Context) float64 {
	v, err := bcs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (bcs *BizCardSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(bcs.fields) > 1 {
		return nil, errors.New("ent: BizCardSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := bcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (bcs *BizCardSelect) BoolsX(ctx context.Context) []bool {
	v, err := bcs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (bcs *BizCardSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = bcs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{bizcard.Label}
	default:
		err = fmt.Errorf("ent: BizCardSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (bcs *BizCardSelect) BoolX(ctx context.Context) bool {
	v, err := bcs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (bcs *BizCardSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := bcs.sql.Query()
	if err := bcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
