// Code generated by mockery v2.10.0. DO NOT EDIT.

package application

import (
	domain "bizCard/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

// RegisterUser provides a mock function with given fields: userRegister
func (_m *MockUserService) RegisterUser(userRegister domain.UserRegister) domain.UserInfo {
	ret := _m.Called(userRegister)

	var r0 domain.UserInfo
	if rf, ok := ret.Get(0).(func(domain.UserRegister) domain.UserInfo); ok {
		r0 = rf(userRegister)
	} else {
		r0 = ret.Get(0).(domain.UserInfo)
	}

	return r0
}
