name: Go

on:
  push:
    branches: [  feature/** ]
  pull_request:
    branches: [ dev,release,main ]

jobs:

  build:
    runs-on: ubuntu-latest
#    services: # 서비스할 목록들 (ex. Redis, Postgresql ...)
#      mysql: # 사용할 서비스 명
#        image: mysql:5.7  # 사용할 서비스의 이미지(도커 개념 기반)
#        env: # 사용할 서비스의 환경설정
#          MYSQL_USER: test
#          MYSQL_PASSWORD: test
#          MYSQL_ROOT_PASSWORD: secret
#          MYSQL_DATABASE: bizcardtest
#        ports: # 열어줄 포트, 8080:3306 형태로도 가능
#          - 13306:3306
#        options: >-  # 서비스에 걸어줄 옵션
#          --health-cmd="mysqladmin ping"
#          --health-interval=10s
#          --health-timeout=5s
#          --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: docker compose start
        run: docker-compose -f "docker-compose.yml" up -d

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Stop containers
          run: docker-compose -f "docker-compose.yml" down
