// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BizCard is the predicate function for bizcard builders.
type BizCard func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
